### ISSUE TITLE
Add user routing based on roles using Auth0

### ISSUE THREAD

**Issue by audiae** [aptus-dev/jobcenter.id-admin#11]
Seems to be stemming from the new firebase migration.

**Comment by audiae** [comment]
Going to change this from " New admins unable to set profile thus unable to go into dashboard ". Need to do routing based on roles using Auth0

**Comment by audiae** [comment]
I can add roles using auth0 rules but haven't found a way how to set up routing using those roles.

**Comment by rumjuice** [comment]
finish routes using roles. only superadmin can access to all pages. admin can't view superadmin page
